# Generated by Django 3.2.8 on 2023-02-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0002_alter_cusdashboard_blockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdashboard',
            name='blockname',
            field=models.CharField(choices=[('IceCreamCorner', 'IceCream Corner'), ('ChocolateCorner', 'Chocolate Corner')], max_length=300, unique=True),
        ),
    ]
