# Generated by Django 3.2.8 on 2023-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheifFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='table', max_length=20)),
                ('dishname', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
