# Generated by Django 3.2.8 on 2023-02-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefModel',
            fields=[
                ('UserId', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=300)),
                ('ChiefName', models.CharField(max_length=300)),
                ('Chief_Experiance', models.CharField(max_length=50)),
                ('C_Post', models.CharField(max_length=50)),
                ('Cheif_AdharCard', models.CharField(max_length=300)),
                ('Chief_Number', models.CharField(max_length=300)),
                ('ChiefAddress', models.CharField(max_length=300)),
                ('ProfileImage', models.FileField(default='None', max_length=600, upload_to='Chief/ChiefProfile/')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('userid', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('PhoneNubmber', models.CharField(blank=True, max_length=20)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('UserId', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=150)),
                ('profilepic', models.FileField(blank=True, upload_to='manager/profilepic')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=14)),
                ('AdharCard', models.CharField(max_length=60)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordsManger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.CharField(default='table', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('TotalCost', models.CharField(max_length=300)),
                ('active', models.CharField(default='0', max_length=5)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=800)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=300)),
                ('quantity', models.CharField(default='1', max_length=10)),
                ('orginalCost', models.CharField(default='0', max_length=10)),
                ('itemCost', models.CharField(max_length=300)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.customerbill')),
            ],
        ),
    ]
